#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: CS499 : Senior Project
#+DATE: <2018-01-20 Sat>
#+AUTHOR: Colton Kopsa
#+EMAIL: Aghbac@Aghbac.local
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.1 (Org mode 9.1.6)

* DONE 01 Status Report
  CLOSED: [2018-01-20 Sat 12:12]
  An idea that I would like to put my efforts towards is natural language
  processing with TensorFlow. This passed week I spent 4 hours getting
  TensorFlow set up on my desktop computer. This consisted of installing Ubuntu
  16.04, installing necessary Nvidia drivers for TensorFlow to utitilize my GPU,
  and running some test programs with TensorFlow to verify everything was
  installed correctly. In addition, I spent some time learning the TensorFlow
  library through their "Getting Started" resource.
* TODO 02 Status Report
  DEADLINE: <2018-01-20 Sat>
  I plan on becoming more familiar with neural networks and how to implement
  those using the TensorFlow library. In particular, I am interested in learning
  more about Convolutional Neural Networks and Recurrent LSTM Neural Networks. An
  example currently exists from TensorFlow that does speech recognition via
  convolutional neural networks, and within the explanation of that example
  recurrent neural networks are mentioned as potentially superior way of doing
  natural language processing.
* TODO 03 Status Report
  DEADLINE: <2018-01-27 Sat>
* TODO 04 SPED Talk
  DEADLINE: <2018-02-03 Sat>
