#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: CS499 : Senior Project
#+DATE: <2018-01-20 Sat>
#+AUTHOR: Colton Kopsa
#+EMAIL: Aghbac@Aghbac.local
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.3.1 (Org mode 9.1.6)

* Status Report Template
** Project Title:
   TensorFlow
** Team Members (if applicable):
   Colton Kopsa & Quade Morrison
** Overall Status (on-schedule, behind, ahead):
** Hours: (replace ## with your hours for each item)
   ## - Number of hours worked since last update
   ## - Total number of hours worked on the project thus far
   ## - Number of total hours anticipated at completion
** Accomplishments:
** Challenges:
** Plans / Goals for next week:
** SPED Talk Insight (Briefly describe an insight or something interesting you learned from the SPED talks this week):
** 9: Other comments for the instructor:
* DONE 01 Status Report
  CLOSED: [2018-01-20 Sat 12:12]
  An idea that I would like to put my efforts towards is natural language
  processing with TensorFlow. This passed week I spent 4 hours getting
  TensorFlow set up on my desktop computer. This consisted of installing Ubuntu
  16.04, installing necessary Nvidia drivers for TensorFlow to utitilize my GPU,
  and running some test programs with TensorFlow to verify everything was
  installed correctly. In addition, I spent some time learning the TensorFlow
  library through their "Getting Started" resource.

* DONE 02 Status Report
  CLOSED: [2018-01-20 Sat 23:01] DEADLINE: <2018-01-20 Sat>
  This week I spent around 4 hours familiarizing myself with the TensorFlow
  library. I worked through a beginning tutorial with the MNIST data-set,
  learning more about using TensorFlow for machine learning. I was able to
  create a linear regression model and train it using a gradient descent
  optimizer which minimized on the cross_entropy of the model. In the end, I was
  able to classify the MNIST data-set to ~92% accuracy. This was an excellent
  way to get my feet wet with the TensorFlow library. I will continue to work
  tutorial after tutorial until I am better versed with TensorFlow to do more
  complex things like working with recurrent neural networks.
* DONE 03 Status Report
  CLOSED: [2018-01-28 Sun 21:08] DEADLINE: <2018-01-27 Sat>
  Br. Burton,
  
  In our brainstorming of ideas we developed some criteria along with some ideas
  that could possibly satisfy those criteria. The criteria were pretty simple:
  - Uses TensorFlow.
  - Causes people to say "Wow that's cool".
  - Has real-world application.
  The following are the ideas we generated towards those goals:
** Free Parking Recognition
   - TensorFlow : Identify the number of free parking spaces in an image.
   - "Wow that's cool" & Real world application : We could integrate it at the
     school and provide students/faculty with information on which parking areas
     have free parking spots.
** Voice Model Production
   - TensorFlow : Train speech models of people, and then use their voice to do
     Text-to-speech.
   - "Wow that's cool" : People could hear themselves say things they've never
     said.
   - Real world application : You could personalize different TTS services that
     you use with voices you're more comfortable with.
** Speech Recognition
   - TensorFlow : Train speech models of people, provide speech-to-text or
     keyword services.
   - "Wow that's cool" : This has less of a wow-factor now that speech
     recognition is a pretty common, but it would still be somewhat impressive.
   - Real world application : Provide a library that would allow people to train
     their own personal voice models and use speech recognition services.
     
   If you have any other suggestions on how to scope these projects, or have any
   interesting projects that meet our criteria, we would love to get any input.
* DONE 04 SPED Talk
  CLOSED: [2018-01-31 Wed 09:53] DEADLINE: <2018-02-03 Sat>
  The following are the guidelines for these presentations:

  They must be short. There is a hard time limit of 5 minutes. This goes very
  quickly, so you will have to plan diligently to ensure that you can cover the
  most important components of the topic in that time period.

  They should focus on the topic you are learning more than your project itself.
  Your goal with this talk is to educate the other students in the course on the
  new computer science topic that you are learning about. You can mention your
  project and how the topic applies, but your talk should be focus on the new
  topic, so it is more generally applicable.

  They should be professional. While the hope is that you will not have to spend
  a lot of time preparing these talks, they should still be professional, and
  not have the appearance of being thrown together last minute.

  When you present, you should add a link to your presentation in the
  appropriate discussion board. Then, you must also upload a link to the
  assignment submission for it.
* DONE 04 Status Report
  CLOSED: [2018-02-03 Sat 13:27] DEADLINE: <2018-02-03 Sat>
** Project Title:
   TensorFlow
** Team Members (if applicable):
   Colton Kopsa & Quade Morrison
** Overall Status (on-schedule, behind, ahead):
   on-schedule
** Hours: (replace ## with your hours for each item)
   - 04 - Number of hours worked since last update
   - 14 - Total number of hours worked on the project thus far
   - ?? - Number of total hours anticipated at completion
** Accomplishments:
   I learned how to work with Convolutional Neural Networks using TensorFlow.
   There was a similar tutorial to the one I did with the MNIST dataset using
   again the MNIST dataset, but with the CNN instead. It walked through building
   a CNN from the ground up using TensorFlow, and then had you train on the
   MNIST dataset and at the end it would print your accuracy. My results were in
   the 98% range which was interesting. I learned that with CNNs you have 3
   phases, the convolutional phase when you add dimensions to your data using
   filters, the pooling phase where you condense the data, and then the normal
   neural net phase when you train and classify your data. So basically, add
   dimensions, make smaller, repeat (if you want), and then finally train your
   classification.
** Challenges:
   Although my knowledge is deepening about TensorFlow and neural networks, we
   still need to hone in on a project.
** Plans / Goals for next week:
   There is a tutorial about recurrent neural networks that I would like to go
   through just to round off the edges of my neural network knowledge. We also
   will be deciding a general direction for our project this week, which we can
   then continue to build on next week by creating a plan for how we will get
   things done.
** SPED Talk Insight (Briefly describe an insight or something interesting you learned from the SPED talks this week):
   I was the SPED Talk speaker.
** 9: Other comments for the instructor:
   None this week.
* DONE 05 Status Report
  CLOSED: [2018-02-10 Sat 15:47] DEADLINE: <2018-02-10 Sat>
** Project Title:
   Voice Synthesis
** Team Members (if applicable):
   Colton Kopsa & Quade Morrison
** Overall Status (on-schedule, behind, ahead):
   On-schedule
** Hours: (replace ## with your hours for each item)
   06 - Number of hours worked since last update
   20 - Total number of hours worked on the project thus far
   126 - Number of total hours anticipated at completion
** Accomplishments:
   - Researched Voice Synthesis methods
   - Discovered dataset that has potential for training
   - Scoped towards phoneme classification
   - Researched how to pull phonemes out of acoustic sentences
** Challenges:
   - Phoneme Extraction
** Plans / Goals for next week:
   If I can figure out a way to build a dataset that maps acoustic signals to
   phonemes then we can train a neural net on it and maybe ease the process of
   phoneme classification. Learning how to go about doing that is what I'd like
   to be researching for next week.
** SPED Talk Insight (Briefly describe an insight or something interesting you learned from the SPED talks this week):
   The SPED Talk is not yet available, but I'll be sure to comment about both
   next week.
** 9: Other comments for the instructor:
   None this week

* DONE 06 Status Report
  CLOSED: [2018-02-19 Mon 13:31] SCHEDULED: <2018-02-15 Thu> DEADLINE: <2018-02-17 Sat>
** Project Title:
   TensorFlow Voice Synthesis
** Team Members (if applicable):
   Colton Kopsa & Quade Morrison
** Overall Status (on-schedule, behind, ahead):
   on-schedule
** Hours: (replace ## with your hours for each item)
   01 - Number of hours worked since last update
   21 - Total number of hours worked on the project thus far
   126 - Number of total hours anticipated at completion
** Accomplishments:
   - Furthered research on phoneme extraction
** Challenges:
   Currently the only thing I've found so far that accomplishes the alignment of
   audio for phoneme extraction is a Bash script from an online course on voice
   synthesis. Although it's something, it requires using what seem to be
   outdated tools.
** Plans / Goals for next week:
   - Work with Quade to find the easiest way for phoneme alignment and
     extraction.
   - Begin scoping in on approaches for training the neural network for phoneme
     classification
** SPED Talk Insight (Briefly describe an insight or something interesting you learned from the SPED talks this week):
*** Last Week's SPED Talk
    I had no idea that Google scripts were capable of making API calls and
    inserting information. It's really cool to see that in practice and I
    thought it was really cool to that Google allows you to add functionality to
    their tools in that way.
*** This Week's SPED Talks
    Interactive graphics are interesting. I didn't know someone would build up a
    framework to do it with SQL and PHP. I feel like those are old web
    technologies that aren't really in style anymore.
    
    React is an interesting technology I haven't learned much about. I thought
    it was interesting the way that he was programatically creating HTML pages.
    I didn't know that was one of the features that React introduced to web
    technologies.
** 9: Other comments for the instructor:
   I understand that my effort this week wasn't quite up to par with the time I
   should be dedicating to senior project. I put that we are still on-schedule
   because I feel like this time can be made up between now and the end of July.
   I'm planned up to put a more adequate amount of time into senior project this
   week.
* DONE 07 Status Report
  CLOSED: [2018-02-25 Sun 18:53] SCHEDULED: <2018-02-20 Tue> DEADLINE: <2018-02-24 Sat>
** Project Title:
   TensorFlow
** Team Members (if applicable):
   Colton Kopsa & Quade Morrison
** Overall Status (on-schedule, behind, ahead):
   on-schedule
** Hours: (replace ## with your hours for each item)
   - 04 - Number of hours worked since last update
   - 25 - Total number of hours worked on the project thus far
   - 126 - Number of total hours anticipated at completion
** Accomplishments:
   - Found /merlin/ a neural net based speech synthesis library
   - Learned more about unit selection speech synthesis vs statistical
     parametric speech synthesis
** Challenges:
   - Should we create a unit-selection speech synthesis or a statistical
     parametric speech synthesis?
   - How are we going to figure out phoneme extraction?
** Plans / Goals for next week:
   - Still figuring out phoneme extraction.
   - Meet with Quade to make plans for project's successful completion
** SPED Talk Insight (Briefly describe an insight or something interesting you learned from the SPED talks this week):
   I didn't know that Windows Universal Applications were a thing. It's
   interesting that Windows has a devkit that allows you to make one application
   work across all of their devices. Google I guess did something similar with
   allowing Chromebooks to run Android applications. I wonder if we'll see iOS
   applications on the MacOS operating system.
** 9: Other comments for the instructor:
* TODO 08 Status Report
  SCHEDULED: <2018-03-02 Fri> DEADLINE: <2018-03-03 Sat>
** Project Title:
   TensorFlow
** Team Members (if applicable):
   Colton Kopsa & Quade Morrison
** Overall Status (on-schedule, behind, ahead):
   on-schedule
** Hours: (replace ## with your hours for each item)
   - 04 - Number of hours worked since last update
   - 25 - Total number of hours worked on the project thus far
   - 126 - Number of total hours anticipated at completion
** Accomplishments:
   - Found /merlin/ a neural net based speech synthesis library
   - Learned more about unit selection speech synthesis vs statistical
     parametric speech synthesis
** Challenges:
   - Should we create a unit-selection speech synthesis or a statistical
     parametric speech synthesis?
   - How are we going to figure out phoneme extraction?
** Plans / Goals for next week:
   - Still figuring out phoneme extraction.
   - Meet with Quade to make plans for project's successful completion
** SPED Talk Insight (Briefly describe an insight or something interesting you learned from the SPED talks this week):
   I didn't know that Windows Universal Applications were a thing. It's
   interesting that Windows has a devkit that allows you to make one application
   work across all of their devices. Google I guess did something similar with
   allowing Chromebooks to run Android applications. I wonder if we'll see iOS
   applications on the MacOS operating system.
** 9: Other comments for the instructor:
* Speech Synthesis
  - Context is something that needs to be stored on each diphone. Metadata for
    each of the diphones essentially. Context is also something that is provided
    through RNNs. It would be interesting to research if that can be helpful here.
** Features
   - dBs
   - frequency
   - spectogram
   - cepstogram
** Ideas
   So, I found the TIMIT dataset that is pretty well done. It has audio and then
   for each thing of audio it has the phonemes
